### ISSUE TITLE
Enhancement to `get_address_abstracts` to support transaction types

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/dora#384]
This feature introduces an update to the results of `get_address_abstracts` to include the following changes:
* inclusion of all transactions association with an address (currently this is filtered to only present transfer invocations)
* addition of a new key `transaction_type`(String) which will be an enum to be used when parsing the formatted transaction data.
  * For example, the existing "parsed" transfer invocations can use a `nep17_transfer` `transaction_type`
* unformatted transaction payloads can simply return the timestamp, hash, and fees

keys should try to maintain alignment across transaction types where possible

**Comment by hal0x2328** [comment]
It is more difficult to merge all transaction information into get_address_abstracts than it might seem since we are returning paginated data from two separate database collections and trying to combine them into a single page. I have an idea for how to do it by running a second search with 15 "OR" conditions in it though. I'll run an experiment and see if the query response time is too slow.

**Comment by lllwvlvwlll** [comment]
superseded by #390
