### ISSUE TITLE
address_txfull endpoint returning NEP-11 transfers as NEP-17 transfers

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#475]
Just mapping a known error that affects other projects as well:

- NEP-11 transfers are being rendered as NEP-17 Transfers

We'll probably tackle this issue when implementing support for NEP-11 transfers in the same endpoint.

## Reference

This is a NFT airdrop transaction, being displayed as many NEP-17 transfers.
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/067430ff-ca7b-4efe-872e-043602f4652a)

**Comment by lllwvlvwlll** [comment]
This display artifact is caused by using the `transfers` key on the `address_txfull` endpoint (which we are moving away from in order to enable the support for variable notification methods (many of which are not `transfers`).  

Instead, we should use the `notifications` field which includes all notifications (including the transfers) for the transaction.  **BOTH** the NEP17 and NEP11 standards include a transfer event so I will propose some solutions below:

1. (short term solution) For this release, we should look at the notification `state`.  If the state is array length 3, it is a NEP-17.  If the state is array length 4, it is a NEP-11.  The NEP-11 version can be treated as an overloaded version of the NEP-17 version.  
  *Note:* This approach is most likely not future proof since another contract standard could include a transfer method with a similar state array length.  It is a good approximation that will be quick to implement so it makes sense for this release.

2. (long term solution) We `should` update the payload format to include some basic contract manifest data including the supported standards.  This would allow us to map the events directly onto the standards definition. Any conflict would then be a standards issue.  This would also allow us to easily map new notification types to the interface.

3. (compute heavy solution) We could query for the manifests of the unique set of contracts presented to pull the supported standards and reference them using the `contract` field in each notification event.  This would work similarly to (2), but would significantly increase load times.

**Comment by picarodias** [comment]
I will forward this discussion to implement solution proposal 1. on dora pages and other projects, such as NWM.

**Comment by melanke** [comment]
Hi @lllwvlvwlll 
Fred put me up with this discussion and it seems easier to implement the "long term solution" right away. I will elaborate:
- Dora already has the "supported standard" information for each contract, it will not be too complex to pull this info.
- We will need to fix the endpoint anyway because it is returning all transfers of the transactions instead of only the ones related to the address, this is causing problems both on Dora and NWM. And maybe it is using too many resources to retrieve the current info (I am not sure if I am clear, let me know if you need more context on this).
- The "short term" solution is a bit complex on the front-end and might take more time to implement than to fix the endpoint. And it would need to be implemented both on Dora and NWM.
- The "short term" solution will fail if a smartcontract doesn't follow the standard and also has a transfer method with the same number of params.

**Comment by lllwvlvwlll** [comment]
I'm a bit resistant to implement the long term solution right away due to the complexity of managing the manifest data.  We can push it as a priority, but I think it will hold up the release of NWM.

@melanke what are your thoughts about pulling and caching the contract manifests in-app?  If you are ok with that, I think the best approach long-term approach would be to simply use the existing method, we can then treat the manifest topic as a separate issue.

The use of a cache would have the same result as the previous proposal, but would separate the areas of concern for the api.  It would also minimize the the compute overhead of more complex queries associated with adding the manifests of UNIQUE(scriptHASH) on one of our most heavily used endpoints. 

### Regarding the manifest topic (and caching): ###

The contract manifest topic is somewhat complex because of the way N3 handles contract updates (manifests are only valid for a specific block range now since the update call does not change the scripthash).  In order to implement the long term solution, we should consider a new `contracts` endpoint which accepts an array of scripthashes and returns an array containing the metadata for each contract.  Each contract payload would need to include an array of data in order to support the way update works.  Example:
```json
[
  {
    "scriptHash": "0xde3fe8d30d98e049272db4b7bd641943b1e86872",
    "payload": [
      {
        "block":  1130000,
        "time":  "1645760140.294000"
        "manifest": {},
        "nef": {},
      },
      {
        "block":  1130000,
        "time":  "1645760140.294000"
        "manifest": {},
        "nef": {},
      }
    ]
  }
]
```

Alternatively, we could simply update the existing `contracts` method to support the historical information and query for it if the scripthash is missing from the cache. 

We would still need a mechanic to invalidate the cache.
