### ISSUE TITLE
Incorrect display of transfer amount when type is bytestring

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/dora#598]
The third transfer in this transaction should be 8 Ghostmarket tokens but Dora shows 0:
https://dora.coz.io/transaction/neo3/testnet/0xa9b61e6a8cc0b8b6d958e8576013ddeaf0179ec8630b486d78b427f074c04c47

The meta indexer shows the correct amount, as well as Neotube:
https://n3t5.neotube.io/transaction/0xa9b61e6a8cc0b8b6d958e8576013ddeaf0179ec8630b486d78b427f074c04c47

It appears that the Dora UI is not correctly displaying the transfer due to the amount being encoded as a bytestring instead of an integer.

**Comment by ixje** [comment]
This is NEO2 with NEP-5 all over again. I don't know what the "meta indexer" is in this case, but it's actually a contract bug because according to the NEP-17 [spec](https://github.com/neo-project/proposals/blob/master/nep-17.mediawiki#transfer-1) the return type should be an "Integer" stack item. 

It is probably good to solve this anyway 🤷‍♂️
